export const hungarianCardNames = {
    "acorn ace": "acorn-ace.png",
    "acorn eight": "acorn-eight.png",
    "acorn king": "acorn-king.png",
    "acorn nine": "acorn-nine.png",
    "acorn ober": "acorn-ober.png",
    "acorn seven": "acorn-seven.png",
    "acorn ten": "acorn-ten.png",
    "acorn unter": "acorn-unter.png",
    "card back": "card_back.png",
    "bell ace": "bell-ace.png",
    "bell eight": "bell-eight.png",
    "bell king": "bell-king.png",
    "bell nine": "bell-nine.png",
    "bell ober": "bell-ober.png",
    "bell seven": "bell-seven.png",
    "bell ten": "bell-ten.png",
    "bell unter": "bell-unter.png",
    "heart ace": "heart-ace.png",
    "heart eight": "heart-eight.png",
    "heart king": "heart-king.png",
    "heart nine": "heart-nine.png",
    "heart ober": "heart-ober.png",
    "heart seven": "heart-seven.png",
    "heart ten": "heart-ten.png",
    "heart unter": "heart-unter.png",
    "leaf ace": "leaf-ace.png",
    "leaf eight": "leaf-eight.png",
    "leaf king": "leaf-king.png",
    "leaf nine": "leaf-nine.png",
    "leaf ober": "leaf-ober.png",
    "leaf seven": "leaf-seven.png",
    "leaf ten": "leaf-ten.png",
    "leaf unter": "leaf-unter.png",
};

export default hungarianCardNames;