export const unoCardNames = {
    "yellow 0": "Y0.png",
    "yellow 1": "Y1.png",
    "yellow 2": "Y2.png",
    "yellow 3": "Y3.png",
    "yellow 4": "Y4.png",
    "yellow 5": "Y5.png",
    "yellow 6": "Y6.png",
    "yellow 7": "Y7.png",
    "yellow 8": "Y8.png",
    "yellow 9": "Y9.png",
    "yellow add 2": "YA2.png",
    "yellow reverse": "YR.png",
    "yellow skip": "YS.png",
    "card back": "card_back.png",
    "blue 0": "B0.png",
    "blue 1": "B1.png",
    "blue 2": "B2.png",
    "blue 3": "B3.png",
    "blue 4": "B4.png",
    "blue 5": "B5.png",
    "blue 6": "B6.png",
    "blue 7": "B7.png",
    "blue 8": "B8.png",
    "blue 9": "B9.png",
    "blue add 2": "BA2.png",
    "blue reverse": "BR.png",
    "blue skip": "BS.png",
    "green 0": "G0.png",
    "green 1": "G1.png",
    "green 2": "G2.png",
    "green 3": "G3.png",
    "green 4": "G4.png",
    "green 5": "G5.png",
    "green 6": "G6.png",
    "green 7": "G7.png",
    "green 8": "G8.png",
    "green 9": "G9.png",
    "green add 2": "GA2.png",
    "green reverse": "GR.png",
    "green skip": "GS.png",
    "red 0": "R0.png",
    "red 1": "R1.png",
    "red 2": "R2.png",
    "red 3": "R3.png",
    "red 4": "R4.png",
    "red 5": "R5.png",
    "red 6": "R6.png",
    "red 7": "R7.png",
    "red 8": "R8.png",
    "red 9": "R9.png",
    "red add 2": "RA2.png",
    "red reverse": "RR.png",
    "red skip": "RS.png",
    "wild pick four": "W4.png",
    "wild color changer": "WC.png",
};

export default unoCardNames;